name: Build

on: workflow_dispatch

jobs:
  build_and_test:
    runs-on: windows-latest
    steps:
      - name: Build
        uses: actions/checkout@v3
      - name: Building...
        run: |
          pyinstaller --distpath dist --onefile --name app --windowed app.py
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: upload-actions
          path: |
            dist